config/routes.rb
Rails.application.routes.draw do

  root 'entries#index'
  resources :entries, only: [:create, :new, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

    def index
        @entries = Entry.all
    end

    def new 
        @entry = Entry.new()
    end

    def create
        @entry = Entry.new(entry_params)
        if @entry.save
            redirect_to root_url
        else
            render :new
        end
    end

    def destroy
        Entry.find(params[:id]).destroy
        redirect_to root_url
    end

    private

    def entry_params
        params.require(:entry).permit(:name, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/views/entries/index.html.erb
<h1 class="text-center py-3">All Entries</h1>

<div class="container">

      <table class="table">
          <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Link</th>
            <th scope="col"></th>
          </tr>
          </thead>
        <% @entries.each do |entry| %>
          <tbody>
          <tr>
            <td><%= entry.name %></td>
            <td><%= entry.link %></td>
            <td><%= button_to "Delete", entry, method: :delete, data: { confirm: "Are you sure you want to delete this Project ?"}, class: "btn btn-primary" %></td>
          </tr>
          </tbody>
        <% end %>

      </table>
</div>

app/views/entries/new.html.erb
<h1 class="text-center py-3">New Entry</h1>

<%= form_with(model: @entry) do |form| %>
  <div class="container col-5">
    <form>
      <div class="form-group py-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group py-3">
        <%= form.label :link %>
        <%= form.text_field :link, class: "form-control" %>
      </div>
      <div class="row py-3">
        <%= form.submit :submit, class: "btn btn-success col m-1" %>
        <%= link_to "Back to home", root_path, class: "btn btn-info col m-1" %>
      </div>
    </form>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyLearnJounral</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render '/shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<!--<div class="navbar">-->
<!--  <div class="nav-home">-->
    <%#= link_to "Ruby learning journal", root_path, class: "nav-link" %>
<!--  </div>-->
<!--  <div class="navbar-link">-->
      <%#= link_to "New Entry", new_entry_path %>
<!--  </div>-->
<!--</div>-->

<div class="navbar navbar-expand-sm navbar-light navbar-guide bg-secondary">
  <div class="container-fluid">
    <div class="navbar-header">
    <%= link_to "Ruby learning journal", root_path, class: "btn nav-brand" %>
    </div>
    <form class="form-search" method="get" id="s" action="/projects">
      <div class="input-append">
        <input type="text" class="input-medium search-query" name="s" placeholder="Search..." value="">
        <button type="submit" class="btn btn-blue search-btn">Go</button>
      </div>
    </form>
    <div class="navbar-link">
      <%= link_to "Home", root_path, class: "btn btn-primary" %>
      <%= link_to "New Entry", new_entry_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>